{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"financials\",\"m_products\",\"m_calendar\",\"m_measures\",\"f_financials\",\"f_financials_attributes_x\",\"f_financials_attributes_y\",\"d_calendar\",\"d_products\",\"_measures\",\"t_calendar\",\"t_financials\",\"t_financials_attributes\",\"getRollingMonths\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "financials",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          " Source = Excel.Workbook(File.Contents(\"C:\\Program Files\\Microsoft Power BI Desktop\\bin\\SampleData\\Financial Sample.xlsx\"), null, true),",
          "    financials_Table = Source{[Item=\"financials\",Kind=\"Table\"]}[Data]",
          "in",
          "    financials_Table"
        ],
        "kind": "m",
        "lineageTag": "6864e8aa-53de-4740-823e-3a53feed4e52",
        "queryGroup": "Extract\\Excel"
      },
      {
        "name": "m_products",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    dProducts = #table(",
          "        { \"Product\", \"Description\", \"ImageUrl\" },",
          "        {",
          "            {\"Paseo\", \"Bicycle\", \"https://decathlonpro.vtexassets.com/arquivos/ids/9626656/16494401945232.jpg\"},",
          "            {\"VTT\", \"Sneaker\", \"\"},",
          "            {\"Velo\", \"Ball\", \"\"},",
          "            {\"Amarilla\", \"Glass\", \"\"},",
          "            {\"Montana\", \"Bag\", \"\"},",
          "            {\"Carretera\", \"Skate\", \"https://decathlonpro.vtexassets.com/arquivos/ids/2355733/yamba-blue-corail-1.jpg\"}",
          "        }",
          "    ),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(dProducts,{{\"Product\", type text}, {\"Description\", type text}, {\"ImageUrl\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "bc4b2aa6-0a3a-422e-b225-5e57227e3b67",
        "queryGroup": "Extract\\M"
      },
      {
        "name": "m_calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // MinYear = 2013,",
          "    // MaxYear = 2014,",
          "    Locale = \"en-GB\",",
          "    MinYear = Date.Year(List.Min(financials[Date])),",
          "    MaxYear = Date.Year(List.Max(financials[Date])),",
          "    BeginDate = #date(MinYear, 1, 1),",
          "    EndDate = #date(MaxYear, 12, 31),",
          "    DaysBetween = Duration.Days(EndDate - BeginDate) + 1,",
          "    DatesList = List.Dates(BeginDate, DaysBetween, #duration(1,0,0,0)),",
          "    ConvertedToTable = Table.FromList(DatesList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    RenamedColumns = Table.RenameColumns(ConvertedToTable,{{\"Column1\", \"Date\"}}),",
          "    ChangedType = Table.TransformColumnTypes(RenamedColumns,{{\"Date\", type date}}),",
          "",
          "    Add_Year = Table.AddColumn(ChangedType, \"Year\", each Date.Year([Date]), Int64.Type),",
          "    Add_Month = Table.AddColumn(Add_Year, \"Month\", each Date.Month([Date]), Int64.Type),",
          "    Add_MonthName = Table.AddColumn(Add_Month, \"Month Name\", each Date.MonthName([Date], Locale), type text),",
          "    Add_YearMonthSort = Table.AddColumn(Add_MonthName, \"YearMonthSort\", each [Year]*100 + [Month], Int64.Type),",
          "    Add_Day = Table.AddColumn(Add_YearMonthSort, \"Day\", each Date.Day([Date]), Int64.Type),",
          "    Add_DayOfWeek = Table.AddColumn(Add_Day, \"Day of Week\", each Date.DayOfWeek([Date]), Int64.Type),",
          "    Add_WeekOfYear = Table.AddColumn(Add_DayOfWeek, \"Week of Year\", each Date.WeekOfYear([Date]), Int64.Type),",
          "    Add_DayOfWeekName = Table.AddColumn(Add_WeekOfYear, \"Day of Week Name\", each Date.DayOfWeekName([Date], Locale), type text),",
          "    Add_Semester = Table.AddColumn(Add_DayOfWeekName, \"Semester\", each if [Month] <= 6 then \"S1\" else \"S2\", type text),",
          "    Add_Quarter = Table.AddColumn(Add_Semester, \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),",
          "    Add_ShortMonth = Table.AddColumn(Add_Quarter, \"Short Month\", each Text.Start([Month Name], 3), type text),",
          "    Add_YearMonth = Table.AddColumn(Add_ShortMonth, \"Year-Month\", each Text.Combine({Text.From([Year], Locale), \"-\", Text.Start([Month Name], 3)})),",
          "",
          "    Add_RelativeToday = Table.AddColumn(Add_YearMonth, \"RelativeToday\", each",
          "            if [Date] < Date.From(DateTime.LocalNow())",
          "            then \"Past\"",
          "            else \"Future\", type text),",
          "    Add_DateFilter = Table.AddColumn(Add_RelativeToday, \"Date Filter\", each",
          "            if [Date] = Date.From(DateTime.LocalNow())",
          "            then \"Today\"",
          "            else Text.From([Date]), type text),",
          "    Add_DiffDaysToday = Table.AddColumn(Add_DateFilter, \"DiffDaysToday\", each Number.From([Date]) - Number.From(Date.From(DateTime.LocalNow())), Int64.Type),",
          "    Add_DayOfWeekShort = Table.AddColumn(Add_DiffDaysToday, \"Day Of Week Short\", each Text.Proper(Text.Range([Day of Week Name], 0, 3))),",
          "    Add_RollingYears = Table.AddColumn(Add_DayOfWeekShort, \"Rolling Years\", each Date.Year(Date.From(DateTime.LocalNow()))- Date.Year([Date]), Int64.Type),",
          "    Add_RollingWeeks = Table.AddColumn(Add_RollingYears, \"Rolling Weeks\", each Date.WeekOfYear(Date.From(DateTime.LocalNow()))- Date.WeekOfYear([Date]), Int64.Type),",
          "    Add_RollingMonths = Table.AddColumn(Add_RollingWeeks, \"Rolling Months\", each getRollingMonths([Date]), Int64.Type)",
          "in",
          "    Add_RollingMonths"
        ],
        "kind": "m",
        "lineageTag": "37c35abd-1101-4289-9934-6b18073baeeb",
        "queryGroup": "Extract\\M"
      },
      {
        "name": "m_measures",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [hidden = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"hidden\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "65165cb5-ab91-4cb7-a9db-9f1eae85164c",
        "queryGroup": "Extract\\M"
      },
      {
        "name": "t_financials",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // Source = Excel.Workbook(File.Contents(\"C:\\Program Files\\Microsoft Power BI Desktop\\bin\\SampleData\\Financial Sample.xlsx\"), null, true),",
          "    // financials_Table = Source{[Item=\"financials\",Kind=\"Table\"]}[Data],",
          "    financials_Table = financials,",
          "    #\"Changed Type\" = Table.TransformColumnTypes(financials_Table,{{\"Segment\", type text}, {\"Country\", type text}, {\"Product\", type text}, {\"Discount Band\", type text}, {\"Units Sold\", type number}, {\"Manufacturing Price\", Int64.Type}, {\"Sale Price\", Int64.Type}, {\"Gross Sales\", type number}, {\"Discounts\", type number}, {\" Sales\", type number}, {\"COGS\", type number}, {\"Profit\", type number}, {\"Date\", type date}, {\"Month Number\", Int64.Type}, {\"Month Name\", type text}, {\"Year\", Int64.Type}}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Discount Band Sort\", each if [Discount Band] = \"None\" then 0 else if [Discount Band] = \"Low\" then 1 else if [Discount Band] = \"Medium\" then 2 else 3, Int64.Type),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"Month Number\", \"Month Name\", \"Year\"}),",
          "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Columns\", \"Index\", 1, 1, Int64.Type)",
          "in",
          " #\"Added Index\""
        ],
        "kind": "m",
        "lineageTag": "4c43f12d-5de5-4e6e-9bc5-a1f68deb3d2b",
        "queryGroup": "Transform"
      },
      {
        "name": "t_financials_attributes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = t_financials,",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Units Sold\", \"Manufacturing Price\", \"Sale Price\", \"Gross Sales\", \"Discounts\", \" Sales\", \"COGS\", \"Profit\", \"Index\"}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Other Columns\", {\"Index\"}, \"Attribute\", \"Value\"),",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", Text.Trim, type text}})",
          "in",
          "    #\"Trimmed Text\""
        ],
        "kind": "m",
        "lineageTag": "e9497e3c-8fb6-4c95-ba5c-2d35377bf83a",
        "queryGroup": "Transform"
      },
      {
        "name": "getRollingMonths",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(Date as date) as number =>",
          "// considerar meses inteiros... contando a partir do dia 1 do mês - mes atual sempre será 0, mes anterior 1 e mes seguinte -1",
          "// [YearDiff]*12+[MonthDiff]",
          "let",
          "    CurrentDate = Date.From(DateTime.FixedLocalNow()),",
          "    CurrentMonth = Date.Month(CurrentDate),",
          "    CurrentYear = Date.Year(CurrentDate),",
          "    Year = Date.Year(Date),",
          "    Month = Date.Month(Date),",
          "    YearDiff = CurrentYear-Year,",
          "    MonthDiff = CurrentMonth-Month,",
          "    Result = YearDiff*12+MonthDiff",
          "in",
          "    Result"
        ],
        "kind": "m",
        "lineageTag": "d2bfecd9-370c-41d0-b28f-d22d818e9247",
        "queryGroup": "Extract\\M"
      },
      {
        "name": "t_calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = m_calendar,",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Day] = 1)) // database with only 01 dates",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "ab6deb6d-2190-4fac-97dc-226c5efcd7f7",
        "queryGroup": "Transform"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Extract"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Extract\\M"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Extract\\Excel"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Transform"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Load"
      }
    ],
    "relationships": [
      {
        "name": "d932ffe8-5283-485b-85e7-fdc205106f13",
        "fromColumn": "Date",
        "fromTable": "d_calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_34c3a72b-45fa-43fa-9fe4-b5d7c937b415"
      },
      {
        "name": "bbfb1741-22a1-43a5-905e-d0075bf63513",
        "fromColumn": "Date",
        "fromTable": "f_financials",
        "toColumn": "Date",
        "toTable": "d_calendar"
      },
      {
        "name": "b2e8aafd-b683-4e7c-b8b1-13e67d621799",
        "fromColumn": "Product",
        "fromTable": "f_financials",
        "toColumn": "Product",
        "toTable": "d_products"
      },
      {
        "name": "3dd8e9ab-21fc-4364-8adb-048578085987",
        "fromColumn": "Index",
        "fromTable": "f_financials_attributes_x",
        "toColumn": "Index",
        "toTable": "f_financials"
      },
      {
        "name": "be7d9375-bfe7-429c-b9f2-2ae93f27f157",
        "fromColumn": "Index",
        "fromTable": "f_financials_attributes_y",
        "toColumn": "Index",
        "toTable": "f_financials"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_edfe2dcd-0c6e-4f95-8386-0ed6cc290eae",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0edff006-1a84-4fd4-b255-3b400e548824",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1574858e-cc2d-440d-b6e9-2539d6d3b27f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7513b90d-6b8b-4ca9-a04c-8be0da696c24",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f0a32da3-2ae9-4656-8c68-5bdc7e4c5567",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "06620857-d642-4fcb-b507-5de1ccc10dd3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "46d1f73a-597d-41e9-8136-5d39b0152430",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "739e21f0-8ddf-4ef8-9a44-6bfa306edf4f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9cc99056-d785-49ce-8abf-cf948fe86005",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "141d2573-cedf-4dfb-9324-25a499ef0e51",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b61dff02-6472-4b73-aae0-0265a32690a6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9854034a-ef66-4382-91cb-5c766e28f44a",
                "ordinal": 3
              }
            ],
            "lineageTag": "026608cb-831c-48ac-99d5-01d05f46e4f5"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "469e9363-dc09-4113-8971-97a0b8fc160f",
        "partitions": [
          {
            "name": "DateTableTemplate_edfe2dcd-0c6e-4f95-8386-0ed6cc290eae",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "d_calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a23f4e3c-d30f-4f62-8d65-8fd963d016b9",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_34c3a72b-45fa-43fa-9fe4-b5d7c937b415"
                },
                "isDefault": true,
                "relationship": "d932ffe8-5283-485b-85e7-fdc205106f13"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3b4c1ed-e881-4145-b426-4d6944449450",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c4be90bc-e6a5-4c53-aa6c-412e3b63d6fe",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45c05ff6-041f-45e4-9b7b-6bf456c68282",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "YearMonthSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5fe4f0c8-11be-48a4-9529-50fc21a878ac",
            "sourceColumn": "YearMonthSort",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ba58047c-819e-49cd-972c-8c4d44612b36",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80b0195f-d42b-4597-8615-cd97b84520d6",
            "sourceColumn": "Day of Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "df35758a-014d-4f48-945b-e922efd5f3de",
            "sourceColumn": "Week of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39719aee-9c62-418d-8247-1a6d78c6e9ad",
            "sourceColumn": "Day of Week Name",
            "summarizeBy": "none"
          },
          {
            "name": "Semester",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2a46919-b729-45ed-86df-0a2c9b1081ba",
            "sourceColumn": "Semester",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8395b9f2-f896-48d6-b66f-938baec03357",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Short Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9855b3b1-7ed5-4bda-b9c2-a5f54a669152",
            "sourceColumn": "Short Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4202d6b3-6442-44b7-bacc-e95f62bc7d69",
            "sortByColumn": "YearMonthSort",
            "sourceColumn": "Year-Month",
            "summarizeBy": "none"
          },
          {
            "name": "RelativeToday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3453d303-e672-4b32-a548-85b18a6c980c",
            "sourceColumn": "RelativeToday",
            "summarizeBy": "none"
          },
          {
            "name": "Date Filter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e708a89f-f40f-4daf-aebf-1c6251e303ba",
            "sourceColumn": "Date Filter",
            "summarizeBy": "none"
          },
          {
            "name": "DiffDaysToday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98931676-09f7-4667-9437-51d027010f94",
            "sourceColumn": "DiffDaysToday",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Of Week Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d5d01fc-8ba4-414b-827b-f218f8d32224",
            "sourceColumn": "Day Of Week Short",
            "summarizeBy": "none"
          },
          {
            "name": "Rolling Years",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36b88e26-1ac7-4a65-9a2f-48ef781938c6",
            "sourceColumn": "Rolling Years",
            "summarizeBy": "sum"
          },
          {
            "name": "Rolling Weeks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f8f2984-ba30-4883-abc6-53df0a900e0f",
            "sourceColumn": "Rolling Weeks",
            "summarizeBy": "sum"
          },
          {
            "name": "Rolling Months",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "469dcc0c-c842-42c6-9edc-a43584f7054f",
            "sourceColumn": "Rolling Months",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d737ebf7-2719-4cb8-8a8f-552d27d61627",
        "partitions": [
          {
            "name": "d_calendar",
            "mode": "import",
            "queryGroup": "Load",
            "source": {
              "expression": [
                "let",
                "    Source = m_calendar",
                "in ",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_34c3a72b-45fa-43fa-9fe4-b5d7c937b415",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ae1302bd-b580-4eb1-bb3c-297641c83667",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b845ea9c-0d90-438a-970d-7cc149574b3c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5e4780c0-0889-4910-9075-4ea925310b65",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "adfe2757-5f39-4ca0-9bc8-6173be468b49",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "676c703b-4a5b-425c-b167-9157ab3e3be4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f55066f4-31ef-4652-bc76-8c561ac0c448",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3e3c8a1a-e2c5-435f-9329-2df86168f378",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6567f5c2-5a02-4bfa-87b2-ab930496c2a4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "75a52e07-fd57-45b7-bb8e-787e3c02d4ef",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b29fb07b-6f49-4354-bbc9-174833096862",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "190e901b-34a4-44da-8361-e74f171b979e",
                "ordinal": 3
              }
            ],
            "lineageTag": "a252bfa9-63c7-47f3-8451-1c9b49ac4f83"
          }
        ],
        "isHidden": true,
        "lineageTag": "97da0fa6-7776-4b03-9f6f-7511da902572",
        "partitions": [
          {
            "name": "LocalDateTable_34c3a72b-45fa-43fa-9fe4-b5d7c937b415",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('d_calendar'[Date])), 1, 1), Date(Year(MAX('d_calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "f_financials",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b542193-24f6-4907-8acc-729a6ad3f3a4",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "8db7b574-cd3b-48bc-8fa2-ffe2d4448381",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70f8b601-eaca-4386-98a5-b48ecb9bd059",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "123d3b99-b7a0-4d9f-9ce8-7c3c9ec3986d",
            "sortByColumn": "Discount Band Sort",
            "sourceColumn": "Discount Band",
            "summarizeBy": "none"
          },
          {
            "name": "Units Sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3083c892-bbb1-461e-be02-c97a6be1b372",
            "sourceColumn": "Units Sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Manufacturing Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4142fd59-2472-4bd0-b91d-e9766bbde202",
            "sourceColumn": "Manufacturing Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Sale Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b12d417-644c-4fc5-8d58-12a6dc87265b",
            "sourceColumn": "Sale Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c93c63ea-42db-44de-9c24-e8a2b8514f6e",
            "sourceColumn": "Gross Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Discounts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "44889935-610c-4091-a601-cd7f3e3353eb",
            "sourceColumn": "Discounts",
            "summarizeBy": "sum"
          },
          {
            "name": " Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "772a0341-44e8-4f5d-9eec-8a6832c99a44",
            "sourceColumn": " Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "COGS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3e2b1516-25a1-4242-82cd-080e7fce23dd",
            "sourceColumn": "COGS",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc4bfe44-6c21-418a-b012-886493750400",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9906bf23-0104-4ba6-87b7-58922c2a4669",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Discounts Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE( f_financials[Discounts],  f_financials[Gross Sales] )",
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "lineageTag": "7d4479be-1284-4fd4-a53e-a79278c44859",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Discount Band Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0a76787a-7157-4b3b-a4c7-a46c864ce7fb",
            "sourceColumn": "Discount Band Sort",
            "summarizeBy": "sum"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "47c99878-2426-41a7-8e19-1de5e4dcc19a",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "15d9062b-11bb-4723-b4d7-cc5a47f1063b",
        "partitions": [
          {
            "name": "f_financials",
            "mode": "import",
            "queryGroup": "Load",
            "source": {
              "expression": [
                "let",
                "    Source = t_financials",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "hidden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "96ea7dba-9d08-4675-a72f-28f88a61d8f0",
            "sourceColumn": "hidden",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a448a99e-d893-4718-a7cd-839b31013141",
        "measures": [
          {
            "name": "Sales",
            "expression": "SUM(f_financials[ Sales])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c97dbf18-d5e9-4b3c-a648-5fa2e759381f"
          },
          {
            "name": "Units Sold",
            "expression": "SUM(f_financials[Units Sold])",
            "formatString": "#,0.00",
            "lineageTag": "fd0c1ecf-c751-4f0d-b236-2f31723eac7e"
          },
          {
            "name": "Avg Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE( f_financials[ Sales] )",
            "lineageTag": "5dbcfcbe-9525-4253-aa25-f06c0cbe4e61"
          },
          {
            "name": "Avg Discounts",
            "expression": "AVERAGE( f_financials[Discounts Pct] )",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "913fd989-24a8-4806-8495-1f6d2b0cdb6a"
          },
          {
            "name": "Last Month Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var __maxDate = MAX(f_financials[Date])",
              "    var __result = CALCULATE(",
              "        [Sales],",
              "        d_calendar[Year] = YEAR(__maxDate) && d_calendar[Month] = MONTH(__maxDate)",
              "    )",
              "    return __result"
            ],
            "lineageTag": "85c4b35c-4339-4193-8e00-13f3e649506a"
          },
          {
            "name": "Prev Month Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var __selectedIndMonth = SELECTEDVALUE(d_calendar[Rolling Months])",
              "    var __result = CALCULATE(",
              "        [Sales],",
              "        FILTER(all(d_calendar), d_calendar[Rolling Months] = (__selectedIndMonth+1) && d_calendar[Month] = SELECTEDVALUE(d_calendar[Month]))",
              "    )",
              "    return __result"
            ],
            "lineageTag": "292a58d7-fac9-4ec6-babc-9fde7535453a"
          }
        ],
        "partitions": [
          {
            "name": "_measures",
            "mode": "import",
            "queryGroup": "Load",
            "source": {
              "expression": [
                "let",
                "    Source = m_measures",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "d_products",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a83bfe8b-2e20-454f-96ed-997efd31f008",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6de5dd42-9195-4c9b-9b2d-8bd15e68b63e",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "ImageUrl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "466e334c-a52f-4866-8d05-982d423b6133",
            "sourceColumn": "ImageUrl",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "68876c3b-aa8f-4679-b76f-63f1a2eba7b2",
        "partitions": [
          {
            "name": "d_products",
            "mode": "import",
            "queryGroup": "Load",
            "source": {
              "expression": [
                "let",
                "    Source = m_products",
                "in ",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "f_financials_attributes_x",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9a10b1f4-4daf-4659-9c21-a9a3f6d1d169",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28b6e330-cad1-42e7-a447-43ea7486f914",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "da2dcd95-39c9-4ea4-998e-09e38f477cc1",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c2c12c34-3327-4f09-8d7f-d78e920f4d60",
        "partitions": [
          {
            "name": "f_financials_attributes_x",
            "mode": "import",
            "queryGroup": "Load",
            "source": {
              "expression": [
                "let",
                "    Source = t_financials_attributes",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "f_financials_attributes_y",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90d1a0dc-14e3-4bee-bb6a-00510b139a69",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf7a79ef-02be-4898-b75a-e65b2cea62c5",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e7161d6b-1e13-4c4f-9335-4e1962a215c5",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ec74eecc-7e92-482c-969b-d7bfa8b96bb4",
        "partitions": [
          {
            "name": "f_financials_attributes_y",
            "mode": "import",
            "queryGroup": "Load",
            "source": {
              "expression": [
                "let",
                "    Source = t_financials_attributes",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}